import "./globals.css";
import { Quicksand } from "next/font/google";
import Header from "./header/page";
import Footer from "./footer/page";

const inter = Quicksand({ subsets: ["latin"] });
export const metadata = {
  title: "Belajar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-gradient-to-r from-stone-50 via-purple-50 to-stone-50">
        <Header />
        <div className="pt-9 lg:pt-24 px-3 lg:px-72 mb-24">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
